name: Build IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Build App
        run: |
          mkdir -p build
          xcodebuild build -sdk iphoneos -configuration Release CODE_SIGNING_ALLOWED=NO -arch arm64
          mkdir -p Payload
          # هذا السطر يبحث عن التطبيق الحقيقي وينسخه
          find . -name "*.app" -exec cp -r {} Payload/ \;
          zip -r MyFinalApp.ipa Payload
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: App-Ready
          path: MyFinalApp.ipa
